// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgUEUtRr82N_gT7C9PLWc7SZMZZxU0mEI',
    appId: '1:960282229932:web:db6f65daef4cf740df3309',
    messagingSenderId: '960282229932',
    projectId: 'bitely-7e91a',
    authDomain: 'bitely-7e91a.firebaseapp.com',
    storageBucket: 'bitely-7e91a.appspot.com',
    measurementId: 'G-BXSJZRMP2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwN7bqO5J6o7x-AyOzx8AxlwppTNI6890',
    appId: '1:960282229932:android:0e3ac41b10c02f45df3309',
    messagingSenderId: '960282229932',
    projectId: 'bitely-7e91a',
    storageBucket: 'bitely-7e91a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgwyNZgfOkLDhgPpPK2zKqhy5X7nMp8mg',
    appId: '1:960282229932:ios:6e67d5fc298b518bdf3309',
    messagingSenderId: '960282229932',
    projectId: 'bitely-7e91a',
    storageBucket: 'bitely-7e91a.appspot.com',
    iosClientId: '960282229932-tpgllpe1o49imvn1leh6tsn85r1lv6jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgwyNZgfOkLDhgPpPK2zKqhy5X7nMp8mg',
    appId: '1:960282229932:ios:6e67d5fc298b518bdf3309',
    messagingSenderId: '960282229932',
    projectId: 'bitely-7e91a',
    storageBucket: 'bitely-7e91a.appspot.com',
    iosClientId: '960282229932-tpgllpe1o49imvn1leh6tsn85r1lv6jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitely',
  );
}
